modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "GNU AGPL 3"

[[mods]]
modId = "wynntils"

#Version is added in build.gradle
version = "${version}"
displayName = "Wynntils"
authors = ["Scyu_", "HeyZeer0", "EHTYCSCYTHE", "SHsuperCM", "coehlrich", "_Bedo_", "HighCrit", "Reticality", "mag_icus", "P0ke", "Incompleteusern"]
description = "The best Wynncraft mod you'll probably find!"
# needs to be "root" file
#logoFile = "assets/wynntils/logo.png"

[[dependencies.wynntils]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wynntils]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

