modLoader = "javafml"
loaderVersion = "[44,)"
issueTrackerURL = "https://github.com/Wynntils/Artemis/issues"
license = "LGPL-3.0-only"

[[mods]]
    modId = "wynntils"
    version = "${version}"  #Version is added in build.gradle
    displayName = "Wynntils"
    authors = "Team Wynntils"
    description = "The best Wynncraft mod you'll probably find!"
    displayURL = "wynntils.com"
    logoFile = "assets/wynntils/logo.png"

[[dependencies.wynntils]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.4]"

[[dependencies.wynntils]]
    modId = "forge"
    mandatory = true
    versionRange = "[44.1.2,)"

