modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "GNU AGPL 3"

[[mods]]
modId = "wynntils"

#Version is added in build.gradle
version = "${version}"
displayName = "Wynntils"
authors = ["Team Wynntils"]
description = "The best Wynncraft mod you'll probably find!"
# needs to be "root" file
#logoFile = "assets/wynntils/logo.png"

[[dependencies.wynntils]]
modId = "forge"
mandatory = true
versionRange = "[40.1.84,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wynntils]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "BOTH"

