modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "https://github.com/Wynntils/Artemis/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "wynntils"
version = "${mod_version}"
displayName = "Wynntils"
authors = "Team Wynntils"
description = "The best Wynncraft mod you'll probably find!"
displayURL = "wynntils.com"
logoFile = "assets/wynntils/logo.png"

[[dependencies.wynntils]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"

[[dependencies.wynntils]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_version_range}"

[[dependencies.wynntils]]
modId = "ias"
type = "incompatible"
reason = "In-Game Account Switcher breaks Wynntils configs"

[[mixins]]
config = "wynntils.mixins.json"

[[mixins]]
config = "wynntils.mixins.neoforge.json"