name: Promote to Release

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  promote-release:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'release'))
    name: Promote main to release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PRIVATE_TOKEN }}

      - name: Merge main into release
        run: |
          git config user.name "WynntilsBot"
          git config user.email "admin@wynntils.com"
  
          git fetch origin main release
  
          git checkout release
          git merge -X theirs origin/main --no-edit
          git push origin release

  clear-changelog:
    needs: promote-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}
          ref: release

      - name: Clear Changelog File
        run: echo "" > CHANGELOG.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}
          commit-message: "chore: Clear changelog"
          title: "chore: Set changelog for new release"
          body: |
            This PR resets the `CHANGELOG.md` file to prepare a new release.
            Edit the file with the relevant release notes for the release.
            
            It is automatically generated and targets the `release` branch.
          branch: set-changelog
          base: release
          labels: auto-generated
          committer: WynntilsBot <admin@wynntils.com>
